### ISSUE TITLE
[Calendar] Дни недели

### ISSUE THREAD

**Issue by pavel-b-novikov** [Silvade/nsudotnet#1]
Нет, дни недели не должны быть захардкожены.

**Comment by Silvade** [comment]
Исправила

**Comment by pavel-b-novikov** [comment]
Я даже не знаю как вам объяснить в чем ошибка. В общем, если вы все еще вынуждены писать 7 почти одинаковых аргументов для string.Format - то это все еще хардкод. 
интересно, а если бы я сказал имена месяцев вывести - вы бы 12 раз скопировали одно и то же?

**Comment by Silvade** [comment]
Переделала
